### PR TITLE
Support nested tuple unpacking in for loops

### PR DESCRIPTION
**Pull request by mtc-mlx**
For example:
~~~
for (key1, val1), (key2, val2) in itertools.pairwise(dict.items()):
    ...
~~~

This is really just "kicking the can down the road" so to speak, because it doesn't allow an infinite number of layers of tuples, but it helps somewhat.

### CODE REVIEW

**Comment by zzzeek** [comment]
how many layers *does* it support?

**Comment by mtc-mlx** [comment]
Only two layers, like in the example I gave. I see I forgot to run flake on the test folder; oops.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 9f953acc75751136919a6ba998ecafacde57be6a of this pull request into gerrit so we can run tests and reviews and stuff

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 9f953acc75751136919a6ba998ecafacde57be6a of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 9f953acc75751136919a6ba998ecafacde57be6a: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/4187

**Comment by zzzeek** [comment]
looks like it needs [pre-commit](https://pre-commit.com/) run, that will fix up the pep8 problems.

also we need a changelog file in the doc/build/unreleased/ folder.   See 925760291d6efec64fda6e9dd1f for an example of this.

**Comment by mtc-mlx** [comment]
Thanks for the guidance :)

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 3f15a87266a36306826d460cddc7699dd62a9c43 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 3f15a87266a36306826d460cddc7699dd62a9c43 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/4187

**Review by CaselIT — APPROVED** [review]

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/4187

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/4187 has been **merged**. Congratulations! :)

**Pull request closed without merging**
