### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by rindeal**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **bourke** to try to get revision a04258282a896237596e926135f0d179686e64ac of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change a04258282a896237596e926135f0d179686e64ac: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3320

**Comment by CaselIT** [comment]
Thanks

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3320 has been **merged**. Congratulations! :)

**Pull request closed without merging**
