### PR TITLE
Include supported Python versions classifiers in setup

### PR DESCRIPTION
**Pull request by mondeja**
This is useful to check quickly what versions of Python are supported through PyPI page.

Python3.4 is deprecated and currently not tested in CI and Python 3.5 will reach EOL in 10 days so I've not included them.

### CODE REVIEW

**Comment by zzzeek** [comment]
great, I can merge this though there's no way to put it on pypi without making a new release and we have nothing to release.

**Comment by zzzeek** [comment]
i might be wrong on that?   can you re-register the setup.py ?  not sure.

**Comment by CaselIT** [comment]
no, you cannot replace a published package. I guess it will wait next release

**Comment by zzzeek** [comment]
there's no sadface icon

**Pull request merged**
