### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by anukaal**

### CODE REVIEW

**Comment by CaselIT** [comment]
I think we could also add `Programming Language :: Python :: 3.10` (after running the tests on it maybe)

**Comment by anukaal** [comment]
> I think we could also add `Programming Language :: Python :: 3.10` (after running the tests on it maybe)

yes ig we can do it !

**Comment by CaselIT** [comment]
I think we are all good for adding 3.10:
```
=================================================================================================================== test session starts ====================================================================================================================
platform linux -- Python 3.10.0rc1, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /mako/.tox/py/bin/python
cachedir: .tox/py/.pytest_cache
rootdir: /mako, configfile: setup.cfg
collected 469 items

test/test_ast.py::AstParseTest::test_argument_list PASSED                                                                                                                                                                                            [  0%]
... lost of tests ...
test/ext/test_linguaplugin.py::ExtractMakoTestCase::test_extract PASSED                                                                                                                                                                              [100%]

============================================================================================================= 464 passed, 5 skipped in 11.59s ==============================================================================================================
_________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________
  py: commands succeeded
  congratulations :)
```

**Comment by anukaal** [comment]
> I think we are all good for adding 3.10:
> 
> ```
> =================================================================================================================== test session starts ====================================================================================================================
> platform linux -- Python 3.10.0rc1, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /mako/.tox/py/bin/python
> cachedir: .tox/py/.pytest_cache
> rootdir: /mako, configfile: setup.cfg
> collected 469 items
> 
> test/test_ast.py::AstParseTest::test_argument_list PASSED                                                                                                                                                                                            [  0%]
> ... lost of tests ...
> test/ext/test_linguaplugin.py::ExtractMakoTestCase::test_extract PASSED                                                                                                                                                                              [100%]
> 
> ============================================================================================================= 464 passed, 5 skipped in 11.59s ==============================================================================================================
> _________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________
>   py: commands succeeded
>   congratulations :)
> ```

Good to go !!!

**Comment by anukaal** [comment]
I have updated the with 3.10 !

**Comment by CaselIT** [comment]
thanks!

**Comment by anukaal** [comment]
> thanks!

It can be merged

**Comment by zzzeek** [comment]
thank you!

**Comment by CaselIT** [comment]
> 
> 
> > thanks!
> 
> It can be merged

Mike's the one who works around here, I just annoy him with questions 🤣😂

**Pull request merged**
